name: feishu-bot-yc
description: 'feishu bot send message'
author: 'kevin'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'send'
  color: 'blue'

# Define your inputs here.
inputs:
  webhook-url:
    description: 'The bot webhook url'
    required: false
  msg-type:
    description: 'The Message type. text/card/cardkit'
    required: true
    default: text
  cardkit-id:
    description: 'If message type is cardkit, the id of cardkit.'
    required: false
  cardkit-version:
    description: 'If message type is cardkit, the version of cardkit.'
    required: false
    default: 1.0.0
  content:
    description: 'The Message content or cardkit params.'
    required: true
  title:
    description: 'If message type is card, the title of card.'
    required: false
  title-color:
    description: 'If message type is card, the title color of card.'
    required: false
    default: green

  # Advance
  use-self-built-app:
    description: 'Use Self-built Application.'
    type: boolean
    required: false
    default: false
  app-id:
    description: 'If you want use Self-built Application. Provide App Id.'
    required: false
  app-secret:
    description: 'If you want use Self-built Application. Provide App Secret.'
    required: false
  chat-id:
    description:
      'If you want use Self-built Application. Provide Group Chat Id.'
    required: false
  update-card:
    description: 'If you want update Sent Card. Set True.'
    type: boolean
    required: false
    default: false
  message-id:
    description: 'If you want update Sent Card. Provide Message Ids.'
    required: false

# Define your outputs here.
outputs:
  message-ids:
    description: 'Self-built Application message id.'

runs:
  using: node20
  main: dist/index.js
